### ISSUE TITLE
Patch theme One Dark failed

### ISSUE THREAD

**Issue by ducpm151061** [kRHYME7/Hyde-cli#32] opened 2024-04-12 07:37 UTC
- [ERROR] gtk-theme set in hypr.theme does not exist in Gtk_*.tar.*

![240412_14h35m02s_screenshot](https://github.com/kRHYME7/Hyde-cli/assets/63179527/6ed28f6e-4bdd-4a4e-bebd-3456d7242eed)
![240412_14h35m29s_screenshot](https://github.com/kRHYME7/Hyde-cli/assets/63179527/269d9498-8abb-4d81-8572-8e9047f1790e)

**Comment by kRHYME7** [comment] 2024-04-12 07:51
please report to the maintainer of the theme first

**Comment by RAprogramm** [comment] 2024-04-12 21:15
try to check this out. i did 
-extract
-compress again 
-and push

**Comment by kRHYME7** [comment] 2024-04-13 00:08
It shoudn't happen though, 

![image](https://github.com/kRHYME7/Hyde-cli/assets/53417443/88afbba9-638c-48bb-b935-f2e89f251fa0)


Please remove other arcs.

**Comment by kRHYME7** [comment] 2024-04-13 01:10
@ducpm151061  Please check

**Comment by RAprogramm** [comment] 2024-04-13 01:21
![240413_10h20m39s_screenshot](https://github.com/kRHYME7/Hyde-cli/assets/70325462/d7a3f716-b962-4a15-a9d2-0b0877b20492)

**Comment by kRHYME7** [comment] 2024-04-13 01:31
Closing this, as confirmed by @RAprogramm 

BTW sir, @RAprogramm  Planning to make a new Discord role. The one who creates Hyde themes, are you interested on making more themes in the future and posibly maintaining it? Looks like couple users love how you setup your one dark theme

**Closed by kRHYME7** 2024-04-13 01:31 UTC

**Comment by RAprogramm** [comment] 2024-04-13 01:36
> Closing this, as confirmed by @RAprogramm 
> 
> BTW sir, @RAprogramm  Planning to make a new Discord role. The one who creates Hyde themes, are you interested on making more themes in the future and possibly maintaining it? Looks like couple users love how you setup your one dark theme. Oh and have the access to manage the Hyde-theme discussion for support

Sure! Why not?
I will be glad if my work, my time or my code will benefit someone or just make it pleasant.
